### PR TITLE
Features

### PR DESCRIPTION
**Pull request by ChuChuNaKu**
This Pull Requests includes:
a simple entity_print test
a calendar test (using selenium)
an updated FeatureContext
and a modified focal point test (using selenium)

### CODE REVIEW

**Comment by balsama** [comment]
Great. At this point would you say that entity_print and calendar are ready for handoff?

**Comment by ChuChuNaKu** [comment]
@balsama Well, I may need to chat with you about entity_print. The installation did not go smoothly and I had to use a work-around to get it to work. That's the only reason I was able to create a working test. My issue was basically this https://www.drupal.org/node/2603716 

Calendar is ready for handoff.

**Comment by balsama** [comment]
Ok. It seems to me that entity print is ready to be incorporated, but calendar is definitely not. (the issue for entity print isn't really an issue - it's just a dependency that we're pulling in with composer)

As such, can you remove the calendar test from the PR?

**Comment by ChuChuNaKu** [comment]
@balsama ok, I'll remove calendar now.

**Comment by ChuChuNaKu** [comment]
@balsama ok, the calendar test has been removed.

**Pull request merged**
